aws_dbt_snowflake_project:
  outputs:
    dev:
      account: < YOUR ACCOUNT DETAILS >
      database: AIRBNB
      password: < YOUR PASSWORD >
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: akaurav123
      warehouse: compute_wh
  target: dev
